### import numpy as np

In [36]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [8]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


### np.full()

In [9]:
print(np.full(5, -2))

[-2 -2 -2 -2 -2]


In [10]:
print(np.full(5, -2))

[-2 -2 -2 -2 -2]


In [12]:
print(np.full(5, -2))

[-2 -2 -2 -2 -2]


In [15]:
print(np.full(2, 3), -2)

[3 3] -2


### np.linespace()

In [19]:
# np.linspace(start, stop, num_of_elements_in_between)
np.linspace(1, 10, 2)

array([ 1., 10.])

In [20]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [23]:
np.linspace((1, 2), (5, 10), num=5)

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]])

### np.diag()

In [30]:
print(np.diag([2, 3, 4, 5], k=1))

[[0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]
 [0 0 0 0 0]]


In [26]:
print(np.diag([2, 3, 4, 5], k=-1))

[[0 0 0 0 0]
 [2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]]


### np.eye()

In [27]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
print(np.eye(5, k=-1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### np.identity()

In [32]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### np.random.rand()

In [33]:
print(np.random.rand(2, 3))

[[0.82779881 0.11636965 0.19602194]
 [0.07620612 0.19387808 0.34516121]]


In [34]:
print(np.random.rand(2, 3))

[[0.85688979 0.47415736 0.4457475 ]
 [0.52872527 0.93264735 0.32407028]]


### np.random.randint

In [37]:
print(np.random.randint(2, 7, size=(3, 7)))

[[2 6 4 6 6 2 2]
 [3 6 6 3 4 4 2]
 [4 3 6 2 5 4 6]]


# Indexing-Numpy-Arrays
### 1D Array:array_name[idx](similar to pyton list)
### 2D Array:array_name[row_idx, col_idx](similar to matrix)
### 1D Array:array_name[dim1idx, dim2_idx, ....., dimx_idx](similar to)

In [38]:
list1 = [1, 2, 3, 4]

In [39]:
list1[2]

3

In [40]:
import numpy as np

In [41]:
array1 = np.array(list1)

In [42]:
array1[2]

3

### Multi Dimensional

In [43]:
list2 = [[1, 2, 3, 4], [1, 3, 5, 7,]]

In [48]:
list2[1][3]

7

In [47]:
array2 =np.array(list2)

In [50]:
array2

array([[1, 2, 3, 4],
       [1, 3, 5, 7]])

In [51]:
array2[1][3]

7