In [7]:
import numpy as np


## One Dimensional Array


In [5]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8]
print(list1[1:7:2])
array1 = np.array(list)

[2, 4, 6]


## Multidimensional Array


In [9]:
list2 = [[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15]]

In [10]:
list2[0][5:]

[6, 7, 8]

In [11]:
array2 = np.array(list2)

In [12]:
array2[0][5:]

array([6, 7, 8])

In [13]:
array2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [14]:
array2[0][5:]

array([6, 7, 8])

In [15]:
array2[0,5:]

array([6, 7, 8])

In [24]:
# [start : stop :step]
array2[:,1:4]

array([[2, 3, 4],
       [3, 5, 7]])

In [17]:
list3 = [[1,2,3,4,5,6,7,8], [1,3,5,7,9,11,13,15],[15,25,9999,376,19,420,786,555]]

In [18]:
array3 = np.array(list3)

In [19]:
array3

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  15,   25, 9999,  376,   19,  420,  786,  555]])

In [23]:
array3[1:,4:7:1]

array([[  9,  11,  13],
       [ 19, 420, 786]])

## Numpy-Methods-Attributes

In [27]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [32]:
a.shape

(2, 3)

In [33]:
a.dtype

dtype('int32')

In [34]:
a.ndim

2

In [42]:
a.flatten()     # make all in one dimension. Trats matrix as lists

array([1, 2, 3, 4, 5, 6])

In [43]:
a.sum()     #sum of all matrix

21

In [44]:
a.max(axis=0)

array([4, 5, 6])

In [45]:
a.max(axis=1)

array([3, 6])

In [49]:
a.argmax(axis=1)        # Indexing of max value

array([2, 2], dtype=int32)

In [48]:
a.reshape((3,2))        # Notice : Product of elements should be conserved

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
b = a.reshape((1,2,3))

In [52]:
b.shape

(1, 2, 3)

In [53]:
m = np.array([[1,2], [3,4]])
n = np.array([[5,6], [7,8]])

In [54]:
np.concatenate((m,n), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
np.concatenate((m,n), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
string = 'hello how are you'

In [59]:
string.split(' ')

['hello', 'how', 'are', 'you']

In [60]:
a = a.reshape(6)

In [61]:
a

array([1, 2, 3, 4, 5, 6])

In [62]:
np.split(a, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [63]:
np.split(a, [2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]